// <auto-generated />
using System;
using FraudDetection.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FraudDetection.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FraudDetectionDbContext))]
    [Migration("20260912134627_AddLargeAmountThresholds")]
    partial class AddLargeAmountThresholds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FraudDetection.Domain.Fraud.FraudFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UUID");

                    b.Property<DateTime>("FlaggedAtUtc")
                        .HasColumnType("TIMESTAMP WITH TIME ZONE");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<Guid>("TransactionEventId")
                        .HasColumnType("UUID");

                    b.HasKey("Id");

                    b.HasIndex("TransactionEventId");

                    b.ToTable("fraud_flags", (string)null);
                });

            modelBuilder.Entity("FraudDetection.Domain.Transactions.TransactionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("UUID");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("UUID");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("TIMESTAMP WITH TIME ZONE");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TIMESTAMP WITH TIME ZONE");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("AccountId", "OccurredAtUtc");

                    b.ToTable("transaction_events", (string)null);
                });

            modelBuilder.Entity("FraudDetection.Infrastructure.Persistence.FraudRuleSettings.LargeAmountThresholdRecord", b =>
                {
                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<decimal>("ThresholdAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Category");

                    b.ToTable("large_amount_thresholds", (string)null);

                    b.HasData(
                        new
                        {
                            Category = "Purchase",
                            ThresholdAmount = 5000m
                        },
                        new
                        {
                            Category = "Withdrawal",
                            ThresholdAmount = 2000m
                        },
                        new
                        {
                            Category = "Transfer",
                            ThresholdAmount = 10000m
                        },
                        new
                        {
                            Category = "Deposit",
                            ThresholdAmount = 20000m
                        },
                        new
                        {
                            Category = "Refund",
                            ThresholdAmount = 3000m
                        });
                });

            modelBuilder.Entity("FraudDetection.Domain.Fraud.FraudFlag", b =>
                {
                    b.HasOne("FraudDetection.Domain.Transactions.TransactionEvent", null)
                        .WithMany("FraudFlags")
                        .HasForeignKey("TransactionEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FraudDetection.Domain.Transactions.TransactionEvent", b =>
                {
                    b.OwnsOne("FraudDetection.Domain.Transactions.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionEventId")
                                .HasColumnType("UUID");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("VARCHAR(3)")
                                .HasColumnName("currency");

                            b1.HasKey("TransactionEventId");

                            b1.ToTable("transaction_events");

                            b1.WithOwner()
                                .HasForeignKey("TransactionEventId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("FraudDetection.Domain.Transactions.TransactionEvent", b =>
                {
                    b.Navigation("FraudFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
